### ISSUE TITLE
Presorting input list fails xcube gen when input data is corrupt

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#246]
**Describe the bug**
When there is a corrupt input file in the list of input files for the xcube gen process, the presorting function does not skip the input file, but the whole process is failing: 

```
 xcube gen -c ~/projects/xcube-services/dcs4cop/xcube-gen-configs/dcs4cop-gen_BC_config_S2_UseCase_UHULL_31UCV.yml ../VITO_S2/0025_UHULL/*31UCV*.nc
/home/xcube/projects/xcube/xcube/core/gen/gen.py:92: UserWarning: append_mode in gen_cube() is deprecated, time slices will now always be inserted, replaced, or appended.
  warnings.warn('append_mode in gen_cube() is deprecated, '
OS error: [Errno -101] NetCDF: HDF error: b'/mnt/dcs4cop/VITO_S2/0025_UHULL/DCS4COP_DEFAULT_S2A_0025_UHULL_20190817T105621Z_31UCV_MPS_V100.nc'
Traceback (most recent call last):
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 198, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/mnt/dcs4cop/VITO_S2/0025_UHULL/DCS4COP_DEFAULT_S2A_0025_UHULL_20190817T105621Z_31UCV_MPS_V100.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xcube/projects/xcube/xcube/cli/main.py", line 52, in main
    exit_code = cli.main(args=args, obj=ctx_obj, standalone_mode=False)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/xcube/projects/xcube/xcube/cli/gen.py", line 128, in gen
    **config)
  File "/home/xcube/projects/xcube/xcube/core/gen/gen.py", line 132, in gen_cube
    input_paths = _get_sorted_input_paths(input_processor, input_paths)
  File "/home/xcube/projects/xcube/xcube/core/gen/gen.py", line 355, in _get_sorted_input_paths
    with xr.open_dataset(input_file) as dataset:
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/xarray/backends/api.py", line 499, in open_dataset
    filename_or_obj, group=group, lock=lock, **backend_kwargs
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 357, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 313, in __init__
    self.format = self.ds.data_model
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 366, in ds
    return self._acquire()
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 360, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 186, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 204, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/mnt/dcs4cop/VITO_S2/0025_UHULL/DCS4COP_DEFAULT_S2A_0025_UHULL_20190817T105621Z_31UCV_MPS_V100.nc'
```

**Expected behavior**
The process should skip the corrupt input file and  continue with the next input file. 

This is my proposed solution:
```
def _get_sorted_input_paths(input_processor, input_paths: Sequence[str]):
    input_path_list = []
    time_list = []
    for input_file in input_paths:
        try:
            with xr.open_dataset(input_file) as dataset:
                t1, t2 = input_processor.get_time_range(dataset)
                time_list.append((t1 + t2) / 2)
                input_path_list.append(input_file)
                tuple_seq = zip(time_list, input_path_list)
        except OSError:
            traceback.print_exc()
            pass

    input_paths = [e[1] for e in sorted(tuple_seq, key=lambda e: e[0])]
    return input_paths
```

**Comment by AliceBalfanz** [comment]
closed by #247
