### ISSUE TITLE
xcube rectify does not accept omitting --var parameter

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#278]
**Describe the bug**
The xcube CLI command `xcube rectify` states in the help section, that when omitting the `--var` parameter, all variables are selected an rectified. 

**To Reproduce**
1. use `xcube rectify` without passing the `--var` parameter
2. See error

```
Rectifying...
Internal error: empty var_names
Traceback (most recent call last):
  File "/home/alicja/Desktop/projects/xcube/xcube/cli/main.py", line 52, in main
    exit_code = cli.main(args=args, obj=ctx_obj, standalone_mode=False)
  File "/home/alicja/miniconda3/envs/xcube/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/alicja/miniconda3/envs/xcube/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alicja/miniconda3/envs/xcube/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alicja/miniconda3/envs/xcube/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/cli/rectify.py", line 113, in rectify
    monitor=print)
  File "/home/alicja/Desktop/projects/xcube/xcube/cli/rectify.py", line 160, in _rectify
    uv_delta=delta)
  File "/home/alicja/Desktop/projects/xcube/xcube/core/rectify.py", line 106, in rectify_dataset
    src_vars = _select_variables(dataset, var_names, geo_coding=src_geo_coding)
  File "/home/alicja/Desktop/projects/xcube/xcube/core/rectify.py", line 179, in _select_variables
    raise ValueError(f'empty var_names')
ValueError: empty var_names
```
**Expected behavior**
The CLI command should rectify all existing variables of the input file when the parameter `--var` is not passed as described in the help section:
```
  -v, --var VARIABLES        Comma-separated list of names of variables to be
                             included or multiple options may be given. If
                             omitted, all variables in INPUT will be
                             reprojected.

```

**Comment by pont-us** [comment]
Diagnosis: when a click "multiple" option is omitted and no explicit default is specified, click supplies an empty tuple as the value (this doesn't seem to be documented anywhere, but can be seen [in the source](https://github.com/pallets/click/blob/499140db5b3090dd1d69c3f4ced7976d942c9c43/src/click/core.py#L1598)). `cli.rectify.rectify` passes the empty tuple through `parse_cli_sequence` (which doesn't change it), and it ends up (via `cli.rectify._rectify` and `core.rectify.rectify_dataset`) as an argument to `core-rectify._select_variables`, which complains (because it expects `None` rather than `()` to indicate "select all variables").

**Comment by pont-us** [comment]
Of the many places where this could be fixed, within the `cli.rectify` function seems the most reasonable: `cli.rectify` calls the `_rectify` function, which specifies `Optional[Sequence[str]]` as the type signature for its `var_names` parameter, indicating that that a possible `None` value is expected here.
