### ISSUE TITLE
ImageGeom.from_dataset(new_cube()) gives "ValueError: invalid  y_min"

### ISSUE THREAD

**Issue by pont-us** [dcs4cop/xcube#303]
**Description**
If a datacube created from `xcube.core.new.new_cube()` (with no arguments specified) is passed to `xcube.core.imgeom.ImageGeom.from_dataset` as the only argument, the latter throws a `ValueError: invalid y_min`.

**Steps to reproduce**
```
from xcube.core.new import new_cube
from xcube.core.imgeom import ImageGeom
image_geom = ImageGeom.from_dataset(new_cube())
```

**Result**
```
Traceback (most recent call last):
  File "bug.py", line 3, in <module>
    image_geom = ImageGeom.from_dataset(new_cube())
  File "/home/pont/loc/xcube-repo/xcube/xcube/core/imgeom.py", line 246, in from_dataset
    ij_denom=ij_denom)
  File "/home/pont/loc/xcube-repo/xcube/xcube/core/imgeom.py", line 284, in _compute_output_geom
    is_geo_crs=geo_coding.is_geo_crs)
  File "/home/pont/loc/xcube-repo/xcube/xcube/core/imgeom.py", line 72, in __init__
    raise ValueError('invalid y_min')
ValueError: invalid y_min
```

**Excepted behaviour**
`ImageGeom.from_dataset(new_cube())` returns a valid `ImageGeom` instance rather than throwing an exception.

**Comment by pont-us** [comment]
Analysis: the exception is thrown as a result of the following test in `ImageGeom.__init__`:

```
if y_min < -90.0 or y_min > 90.0 or y_min + h * xy_res > 90.0:
    raise ValueError('invalid y_min')
```

When `__init__` is called via `from_dataset(new_cube())`, `y_min`=89.5, `h`=254, and `xy_res`=0.7071067811865475, so `y_min + h * xy_res` =~ 90.105 and the last part of the test fails. The most likely culprit would appear to be a miscalculation of the height in `imgeom._compute_output_geom`.

**Comment by pont-us** [comment]
The width and height are calculated in lines 276 and 277 of `imgeom.py`:

```
    dst_width = 1 + math.floor((src_x_max - src_x_min) / src_xy_res)
    dst_height = 1 + math.floor((src_y_max - src_y_min) / src_xy_res)
```

They are rounded up to the nearest integer. In most cases this is probably reasonable behaviour: the value must be rounded to *some* integer, and rounding up ensures that the entire requested area is covered (with some additional sub-pixel margin). This only becomes a problem in the special case where the rounded-up value ends up corresponding to >180° latitude or >360° longitude. The most reasonable solution is probably an explicit check for these cases, retaining the current behaviour otherwise.

Note: in the case of the `new.new_cube()` output, it happens that the width does not exceed 360°, but this is not guaranteed in general -- it just happens that `359 / xy_res` =~ 507.70, so the rounding behaviour doesn't add enough to take `width * xy_res` over 360. This isn't guaranteed, though: for instance, with an `xy_oversampling` parameter of 1.3, a width corresponding to ~360.04° results. So the width as well as the height needs to be bounds checked.
