### ISSUE TITLE
Readthedocs compilation not complete

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#355]
**Describe the bug**
The documentation on Readthedocs is not listing all configured docstrings. The issue does not exist when compiling the documentation locally within the `xcube/docs` directory with `make html`. 

read the docs of master branch: https://xcube.readthedocs.io/en/latest/api.html 
rst file with autofunctions pointing to the modules: https://github.com/dcs4cop/xcube/blob/master/docs/source/api.rst

When checking the Read the docs build for the latest code version on https://readthedocs.org/ the step:

` python /home/docs/checkouts/readthedocs.org/user_builds/xcube/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees -D language=en . _build/html`

produces many warnings. The xcube modules with warnings do not show the docstrings within the read the docs documentation: 
```
Running Sphinx v3.2.1
loading translations [en]... done
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 30 source files that are out of date
updating environment: [new config] 30 added, 0 changed, 0 removed
reading sources... [  3%] api
reading sources... [  6%] cli
reading sources... [ 10%] cli/xcube
reading sources... [ 13%] cli/xcube_chunk
reading sources... [ 16%] cli/xcube_compute
reading sources... [ 20%] cli/xcube_dump
reading sources... [ 23%] cli/xcube_edit
reading sources... [ 26%] cli/xcube_extract
reading sources... [ 30%] cli/xcube_gen
reading sources... [ 33%] cli/xcube_grid
reading sources... [ 36%] cli/xcube_level
reading sources... [ 40%] cli/xcube_optimize
reading sources... [ 43%] cli/xcube_prune
reading sources... [ 46%] cli/xcube_resample
reading sources... [ 50%] cli/xcube_serve
reading sources... [ 53%] cli/xcube_tile
reading sources... [ 56%] cli/xcube_vars2dim
reading sources... [ 60%] cli/xcube_verify
reading sources... [ 63%] cubespec
reading sources... [ 66%] devguide
reading sources... [ 70%] examples
reading sources... [ 73%] examples/xcube_gen
reading sources... [ 76%] examples/xcube_serve
reading sources... [ 80%] index
reading sources... [ 83%] installation
reading sources... [ 86%] overview
reading sources... [ 90%] plugins
reading sources... [ 93%] storeconv
reading sources... [ 96%] viewer
reading sources... [100%] webapi

/home/docs/checkouts/readthedocs.org/user_builds/xcube/envs/latest/lib/python3.7/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
WARNING: autodoc: failed to import function 'dsio.open_cube' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'dsio.write_cube' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'gen.gen_cube' from module 'xcube.core.gen'; the following exception was raised:
No module named 'yaml'
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/xcube/core/new.py:docstring of xcube.core.new.new_cube:27: WARNING: Inline interpreted text or phrase reference start-string without end-string.
WARNING: autodoc: failed to import function 'compute.compute_cube' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'evaluate.evaluate_dataset' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'extract.get_cube_values_for_points' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'extract.get_cube_point_indexes' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'extract.get_cube_values_for_indexes' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'extract.get_dataset_indexes' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'timeseries.get_time_series' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'resample.resample_in_time' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'vars2dim.vars_to_dim' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'chunk.chunk_dataset' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'select_vars' from module 'xcube.core.select'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcube/envs/latest/lib/python3.7/site-packages/sphinx/util/inspect.py", line 325, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'xcube.core.select' has no attribute 'select_vars'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcube/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 106, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcube/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 289, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcube/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 2186, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcube/envs/latest/lib/python3.7/site-packages/sphinx/util/inspect.py", line 341, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: select_vars

WARNING: autodoc: failed to import function 'geom.clip_dataset_by_geometry' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'geom.mask_dataset_by_geometry' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'geom.rasterize_features' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'edit.edit_metadata' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'update.update_dataset_attrs' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'update.update_dataset_spatial_attrs' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'update.update_dataset_temporal_attrs' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'verify.assert_cube' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'verify.verify_cube' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'level.compute_levels' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'level.read_levels' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'level.write_levels' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import function 'geom.convert_geometry' from module 'xcube.core'; the following exception was raised:
No module named 'yaml'
WARNING: autodoc: failed to import class 'store.CubeStore' from module 'xcube.core'; the following exception was raised:
No module named 'jsonschema'
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_gen.rst:8: WARNING: Duplicate explicit target name: "cf conventions".
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_gen.rst:134: WARNING: Duplicate target name, cannot be used as a unique reference: "cf conventions".
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:136: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:149: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:162: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:169: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:170: WARNING: Title underline too short.

Remotely Stored xcube Datasets
-----------------------------
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:170: WARNING: Title underline too short.

Remotely Stored xcube Datasets
-----------------------------
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:226: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:282: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:320: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:384: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:426: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:79: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:86: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:86: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:86: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:98: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:98: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:94: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:100: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:100: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_tile.rst:100: WARNING: Inline interpreted text or phrase reference start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  3%] api
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/storeconv.md: WARNING: document isn't included in any toctree
writing output... [  6%] cli
writing output... [ 10%] cli/xcube
writing output... [ 13%] cli/xcube_chunk
writing output... [ 16%] cli/xcube_compute
writing output... [ 20%] cli/xcube_dump
writing output... [ 23%] cli/xcube_edit
writing output... [ 26%] cli/xcube_extract
writing output... [ 30%] cli/xcube_gen
writing output... [ 33%] cli/xcube_grid
writing output... [ 36%] cli/xcube_level
writing output... [ 40%] cli/xcube_optimize
writing output... [ 43%] cli/xcube_prune
writing output... [ 46%] cli/xcube_resample
writing output... [ 50%] cli/xcube_serve
writing output... [ 53%] cli/xcube_tile
writing output... [ 56%] cli/xcube_vars2dim
writing output... [ 60%] cli/xcube_verify
writing output... [ 63%] cubespec
writing output... [ 66%] devguide
writing output... [ 70%] examples
writing output... [ 73%] examples/xcube_gen
writing output... [ 76%] examples/xcube_serve
writing output... [ 80%] index
writing output... [ 83%] installation
writing output... [ 86%] overview
writing output... [ 90%] plugins
writing output... [ 93%] storeconv
writing output... [ 96%] viewer
writing output... [100%] webapi

/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:86: WARNING: unknown document: cli/xcube_level
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:103: WARNING: unknown document: cli/xcube_chunk
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:129: WARNING: undefined label: example (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:132: WARNING: undefined label: authentication (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:132: WARNING: undefined label: dataset-attribution (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:132: WARNING: undefined label: datasets (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:132: WARNING: undefined label: place-groups (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:132: WARNING: undefined label: styles (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:190: WARNING: undefined label: locally-stored-xcube-datasets (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:190: WARNING: undefined label: on-the-fly-generation-of-xcube-datasets (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:215: WARNING: undefined label: styles (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:218: WARNING: undefined label: place-groups (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:222: WARNING: undefined label: authentication (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:252: WARNING: undefined label: remotely-stored-xcube-datasets (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/cli/xcube_serve.rst:277: WARNING: undefined label: authentication (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/examples/xcube_gen.rst:30: WARNING: unknown document: cli/xcube dump
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/examples/xcube_gen.rst:155: WARNING: unknown document: cli/xcube optimize
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/examples/xcube_gen.rst:168: WARNING: unknown document: cli/xcube prune
/home/docs/checkouts/readthedocs.org/user_builds/xcube/checkouts/latest/docs/source/examples/xcube_gen.rst:178: WARNING: unknown document: cli/xcube dump
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [  6%] examples/../_static/screenshot_xcube_viewer_sst_docu.png
copying images... [ 13%] _static/images/viewer/screenshot_overview.png
copying images... [ 20%] _static/images/viewer/screenshot_datasets.png
copying images... [ 26%] _static/images/viewer/screenshot_variables.png
copying images... [ 33%] _static/images/viewer/screenshot_timeseries.png
copying images... [ 40%] _static/images/viewer/screenshot_change_variable.png
copying images... [ 46%] _static/images/viewer/screenshot_timeseries_second_variable.png
copying images... [ 53%] _static/images/viewer/screenshot_timeseries_second_location.png
copying images... [ 60%] _static/images/viewer/screenshot_polygon.png
copying images... [ 66%] _static/images/viewer/screenshot_circle.png
copying images... [ 73%] _static/images/viewer/screenshot_calendar.png
copying images... [ 80%] _static/images/viewer/screenshot_timeline.png
copying images... [ 86%] _static/images/viewer/screenshot_settings.png
copying images... [ 93%] _static/images/viewer/screenshot_value_ranges.png
copying images... [100%] _static/images/viewer/screenshot_colormap.png

copying static files... ... done
copying readthedocs static files... done
copying searchtools... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 73 warnings.

The HTML pages are in _build/html. 
```

**Comment by AliceBalfanz** [comment]
fixed by #356
