### ISSUE TITLE
Meaningful Error message for request configs which are outside available time range (xcube gen2) with --stores

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#430]
**Is your feature request related to a problem? Please describe.**
When requesting a data cube which has a time range outside the available time range an error occurs while generating the cube. 
The error message is not very helpful: `ZeroDivisionError: division by zero`. It would be great to get a message like: "The requested time period is not available." or something like this :)

To reproduce: branch 0.7.x

The json config used to reproduce: 
```
{
  "input_configs": [
    {
      "store_id": "@cop_services_data",
      "data_id": "OCEANCOLOUR_BAL_CHL_L3_NRT_OBSERVATIONS_009_049.zarr",
      "open_params": {}
    }
  ],
  "cube_config": {
    "variable_names": [
      "CHL"
    ],
    "bbox": [
      12.5,
      54.0,
      27.5,
      62.0
    ],
    "spatial_res": 0.041666666666666664,
    "crs": "WGS84",
    "time_range": [
      "2018-06-01",
      "2018-07-01"
    ],
    "time_period": "1M",
    "chunks": {
      "time": 1,
      "lat": 1024,
      "lon": 1024
    }
  },
  "output_config": {
    "store_id": "s3",
    "data_id": "nc2zarr-OC-BAL_CHL.zarr",
    "replace": true,
    "store_params": {
      "bucket_name": "eurodatacube-scratch"
    }
  }
}
```

with the following traceback:
```
Traceback (most recent call last):
  File "test_json_configs.py", line 245, in test_gen2_json_configs
    output = self.invoke_cli(['--traceback', 'gen2', json_config_path,
  File "test_json_configs.py", line 23, in invoke_cli
    return self.runner.invoke(cli, args, catch_exceptions=False)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/click/testing.py", line 329, in invoke
    cli.main(args=args or (), prog_name=prog_name, **extra)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xcube/projects/xcube/xcube/cli/gen2.py", line 124, in gen2
    generator.generate_cube()
  File "/home/xcube/projects/xcube/xcube/core/gen2/generator.py", line 176, in generate_cube
    data_id = cube_writer.write_cube(cube)
  File "/home/xcube/projects/xcube/xcube/core/gen2/writer.py", line 53, in write_cube
    data_id = writer.write_data(cube,
  File "/home/xcube/projects/xcube/xcube/core/store/stores/s3.py", line 243, in write_data
    self._new_s3_writer(writer_id).write_data(data, data_id=path, replace=replace, **write_params)
  File "/home/xcube/projects/xcube/xcube/core/store/accessors/dataset.py", line 313, in write_data
    data.to_zarr(s3fs.S3Map(root=f'{bucket_name}/{data_id}' if bucket_name else data_id,
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/xarray/core/dataset.py", line 1745, in to_zarr
    return to_zarr(
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/xarray/backends/api.py", line 1482, in to_zarr
    writes = writer.sync(compute=compute)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/xarray/backends/common.py", line 155, in sync
    delayed_store = da.store(
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/array/core.py", line 1022, in store
    result.compute(**kwargs)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/base.py", line 281, in compute
 File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/base.py", line 563, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/threaded.py", line 76, in get
    results = get_async(
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/local.py", line 487, in get_async
    raise_exception(exc, tb)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/local.py", line 317, in reraise
    raise exc
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/array/core.py", line 3924, in store_chunk
    return load_store_chunk(x, out, index, lock, return_stored, False)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/dask/array/core.py", line 3913, in load_store_chunk
    out[index] = np.asanyarray(x)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/zarr/core.py", line 1122, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/zarr/core.py", line 1217, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/zarr/core.py", line 1506, in _set_basic_selection_nd
    indexer = BasicIndexer(selection, self)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/zarr/indexing.py", line 280, in __init__
    dim_indexer = SliceDimIndexer(dim_sel, dim_len, dim_chunk_len)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/zarr/indexing.py", line 114, in __init__
    self.nchunks = ceildiv(self.dim_len, self.dim_chunk_len)
  File "/home/xcube/miniconda3/envs/xcube/lib/python3.8/site-packages/zarr/indexing.py", line 98, in ceildiv
    return math.ceil(a / b)
ZeroDivisionError: division by zero
```

When adjusting the time range to available dates, like below, the requested cube is generated without problems:
```
{
  "input_configs": [
    {
      "store_id": "@cop_services_data",
      "data_id": "OCEANCOLOUR_BAL_CHL_L3_NRT_OBSERVATIONS_009_049.zarr",
      "open_params": {}
    }
  ],
  "cube_config": {
    "variable_names": [
      "CHL"
    ],
    "bbox": [
      12.5,
      54.0,
      27.5,
      62.0
    ],
    "spatial_res": 0.041666666666666664,
    "crs": "WGS84",
    "time_range": [
      "2019-06-01",
      "2019-07-01"
    ],
    "time_period": "1M",
    "chunks": {
      "time": 1,
      "lat": 1024,
      "lon": 1024
    }
  },
  "output_config": {
    "store_id": "s3",
    "data_id": "nc2zarr-OC-BAL_CHL.zarr",
    "replace": true,
    "store_params": {
      "bucket_name": "eurodatacube-scratch"
    }
  }
}
```

**Comment by AliceBalfanz** [comment]
Works great, thanks for implementing!
