### ISSUE TITLE
WMTS capabilities request

### ISSUE THREAD

**Issue by tiagoams** [dcs4cop/xcube#569]
When using OWSlib to request WMTS capabilities I get an error:

```
base_url = 'https://datacube.cefas.co.uk/xcube/wmts'
wmts = WebMapTileService(base_url)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tiago/.conda/envs/owslib/lib/python3.10/site-packages/owslib/wmts.py", line 178, in __init__
    self._capabilities = reader.read(self.url, self.vendor_kwargs)
  File "/home/tiago/.conda/envs/owslib/lib/python3.10/site-packages/owslib/wmts.py", line 862, in read
    u = openURL(spliturl[0], spliturl[1], method='Get', headers=self.headers, auth=self.auth)
  File "/home/tiago/.conda/envs/owslib/lib/python3.10/site-packages/owslib/util.py", line 214, in openURL
    req.raise_for_status()
  File "/home/tiago/.conda/envs/owslib/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://datacube.cefas.co.uk/xcube/wmts?service=WMTS&request=GetCapabilities&version=1.0.0
```

**Expected behavior**
With an example USGS wmts server:
```
from owslib.wmts import WebMapTileService
base_url= 'https://mrdata.usgs.gov/mapcache/wmts'
wmts = WebMapTileService(base_url)
wmts
<owslib.wmts.WebMapTileService object at 0x7f01f39d24d0>
```

The API format specified in the swaggerhub works, but I expected owslib to be using the standard behaviour.

```
curl https://datacube.cefas.co.uk/xcube/wmts/1.0.0/WMTSCapabilities.xml
```

Using xcube server 0.8.1

**Comment by tiagoams** [comment]
I found a workaround for when the service has a different url so this is no longer an issue:

```
wmts = WebMapTileService('https://datacube.cefas.co.uk/xcube/wmts/1.0.0/WMTSCapabilities.xml')
wmts
<owslib.wmts.WebMapTileService object at 0x7f01f3882350>
```
