### ISSUE TITLE
xcube serve to skip failing datasets

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#789]
**Is your feature request related to a problem? Please describe.**
When a xcube server configuration contains a dataset which cannot be loaded, the server fails and even datacubes which work nicely are not displayed.
**Describe the solution you'd like**
I would like the failing dataset to be skipped with a log entry of the error message and that it is skipped. Maybe also the viewer could show a popup which needs to be closed with informing the user about a skipped dataset.

**Describe alternatives you've considered**
There is no alternative especially when we expect users to view their own datacubes in with xcube viewer - there we (xcube dev team) cannot have a look into each single failing datacube. 

**Additional context**
Current tested version: 
xcube Viewer version 0.13.0-dev.0
xcube Server version 0.13.0.dev8

**Comment by forman** [comment]
@AliceBalfanz can you please provide an example of a dataset that causes the issue. What exactly happens? Subsequent datasets are not loaded or the server does even not start and exits immediately? You should have a stack trace of the exception caused by the "bad" dataset and that prevents others from loading. Start xcube server using `xcube --traceback serve ...`.

**Comment by AliceBalfanz** [comment]
I will provide the configuration seperatly. 

The viewer shows Internal Server Error:
![image](https://user-images.githubusercontent.com/23457217/216275421-e51e375f-c29e-4565-be8a-eebc9da3ecf1.png)

And the traceback is: 
```
$ xcube --traceback --loglevel INFO serve -c /home/alicja/Desktop/projects/service-xcube-viewer-apps/deep-esdl/dev/api/server-
config.yaml -v --traceperf --open-viewer
```

```
[I 2023-02-02 09:50:23,746 xcube] Configuration loaded: /home/alicja/Desktop/projects/service-xcube-viewer-apps/deep-esdl/dev/api/server-config.yaml
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 'auth'
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 'styles'
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 'viewer'
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 'meta'
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 'places'
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 'datasets'
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 'tiles'
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 'timeseries'
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 's3'
[I 2023-02-02 09:50:25,687 xcube] Loaded service API 'ows.wmts'
[I 2023-02-02 09:50:25,711 xcube] Applying initial configuration...
[I 2023-02-02 09:50:25,712 xcube] Scanning store 'deep-esdl'
[I 2023-02-02 09:50:25,801 aiobotocore.credentials] Found credentials in shared credentials file: ~/.aws/credentials
[I 2023-02-02 09:50:26,624 xcube] Scanning store 'deep-esdl-out'
[I 2023-02-02 09:50:27,138 xcube] Starting service...
[I 2023-02-02 09:50:27,138 xcube] Service running, listening on 0.0.0.0:8080
[I 2023-02-02 09:50:27,138 xcube] Try http://127.0.0.1:8080/openapi.html
[I 2023-02-02 09:50:27,138 xcube] Press CTRL+C to stop service
[W 2023-02-02 09:50:30,506 tornado.access] 404 GET /viewer/config/config.json (127.0.0.1) 1.07ms
[W 2023-02-02 09:50:30,506 tornado.access] 404 GET /viewer/config/config.json (127.0.0.1) 1.07ms
[W 2023-02-02 09:50:30,506 tornado.access] 404 GET /viewer/config/config.json (127.0.0.1) 1.07ms
[I 2023-02-02 09:50:31,116 tornado.access] 200 GET / (127.0.0.1) 572.66ms
[I 2023-02-02 09:50:31,116 tornado.access] 200 GET / (127.0.0.1) 572.66ms
2023-02-02 09:50:31,116 - tornado.access - INFO - 200 GET / (127.0.0.1) 572.66ms
[I 2023-02-02 09:50:31,116 tornado.access] 200 GET / (127.0.0.1) 572.66ms
[I 2023-02-02 09:50:31,125 xcube] Collecting datasets for granted scopes None
[I 2023-02-02 09:50:31,126 xcube] Collected dataset deep-esdl~esdc-8d-0.25deg-1x720x1440-3.0.1.zarr
[I 2023-02-02 09:50:31,126 xcube] Collected dataset deep-esdl~black-sea-1x1024x1024.levels
[I 2023-02-02 09:50:31,126 xcube] Collected dataset deep-esdl-out~SMOS-snow-1x720x720_v3.zarr
[I 2023-02-02 09:50:31,126 xcube] Collected dataset deep-esdl-out~LC-1x2160x2160_v1.levels
[I 2023-02-02 09:50:31,126 xcube] Loading details for dataset deep-esdl~esdc-8d-0.25deg-1x720x1440-3.0.1.zarr
[I 2023-02-02 09:50:31,997 xcube] Opened dataset 'deep-esdl~esdc-8d-0.25deg-1x720x1440-3.0.1.zarr' from data store 'deep-esdl': took 870.22ms
[I 2023-02-02 09:50:32,704 xcube] Opened dataset 'esdc-time-optimized' from data store 'deep-esdl': took 582.91ms
[I 2023-02-02 09:50:33,905 xcube] Loading details for dataset deep-esdl~black-sea-1x1024x1024.levels
[I 2023-02-02 09:50:33,909 xcube] Opened dataset 'deep-esdl~black-sea-1x1024x1024.levels' from data store 'deep-esdl': took 4.28ms
[I 2023-02-02 09:50:43,469 xcube] Opened dataset 'black-sea-time-optimized' from data store 'deep-esdl': took 3776.22ms
[I 2023-02-02 09:50:43,818 xcube] Loading details for dataset deep-esdl-out~SMOS-snow-1x720x720_v3.zarr
[I 2023-02-02 09:50:44,111 xcube] Opened dataset 'deep-esdl-out~SMOS-snow-1x720x720_v3.zarr' from data store 'deep-esdl-out': took 292.94ms
[E 2023-02-02 09:50:49,050 tornado.application] Uncaught exception GET /datasets?details=1 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/datasets?details=1', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/alicja/miniconda3/envs/xcube/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/alicja/Desktop/projects/xcube/xcube/server/webservers/tornado.py", line 354, in get
    await self._call_method('get', *args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/server/webservers/tornado.py", line 374, in _call_method
    method(*args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/routes.py", line 77, in get
    response = get_datasets(self.ctx,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/controllers.py", line 145, in get_datasets
    get_dataset(ctx, ds_id,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/controllers.py", line 187, in get_dataset
    ml_ds = ctx.get_ml_dataset(ds_id)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 181, in get_ml_dataset
    ml_dataset, _ = self._get_dataset_entry(ds_id)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 599, in _get_dataset_entry
    self._set_dataset_entry(self._create_dataset_entry(ds_id))
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 612, in _create_dataset_entry
    ml_dataset = self._open_ml_dataset(dataset_config)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 640, in _open_ml_dataset
    ml_dataset = BaseMultiLevelDataset(dataset)
  File "/home/alicja/Desktop/projects/xcube/xcube/core/mldataset/base.py", line 63, in __init__
    grid_mapping = GridMapping.from_dataset(base_dataset,
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/base.py", line 669, in from_dataset
    return new_grid_mapping_from_dataset(
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/dataset.py", line 65, in new_grid_mapping_from_dataset
    grid_mappings = [
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/dataset.py", line 66, in <listcomp>
    new_grid_mapping_from_coords(x_coords=gmp.coords.x,
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/coords.py", line 257, in new_grid_mapping_from_coords
    assert_true(x_res > 0 and y_res > 0,
  File "/home/alicja/Desktop/projects/xcube/xcube/util/assertions.py", line 125, in assert_true
    raise exception_type(message)
RuntimeError: internal error: x_res and y_res could not be determined
[E 2023-02-02 09:50:49,050 tornado.application] Uncaught exception GET /datasets?details=1 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/datasets?details=1', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/alicja/miniconda3/envs/xcube/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/alicja/Desktop/projects/xcube/xcube/server/webservers/tornado.py", line 354, in get
    await self._call_method('get', *args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/server/webservers/tornado.py", line 374, in _call_method
    method(*args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/routes.py", line 77, in get
    response = get_datasets(self.ctx,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/controllers.py", line 145, in get_datasets
    get_dataset(ctx, ds_id,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/controllers.py", line 187, in get_dataset
    ml_ds = ctx.get_ml_dataset(ds_id)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 181, in get_ml_dataset
    ml_dataset, _ = self._get_dataset_entry(ds_id)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 599, in _get_dataset_entry
    self._set_dataset_entry(self._create_dataset_entry(ds_id))
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 612, in _create_dataset_entry
    ml_dataset = self._open_ml_dataset(dataset_config)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 640, in _open_ml_dataset
    ml_dataset = BaseMultiLevelDataset(dataset)
  File "/home/alicja/Desktop/projects/xcube/xcube/core/mldataset/base.py", line 63, in __init__
    grid_mapping = GridMapping.from_dataset(base_dataset,
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/base.py", line 669, in from_dataset
    return new_grid_mapping_from_dataset(
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/dataset.py", line 65, in new_grid_mapping_from_dataset
    grid_mappings = [
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/dataset.py", line 66, in <listcomp>
    new_grid_mapping_from_coords(x_coords=gmp.coords.x,
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/coords.py", line 257, in new_grid_mapping_from_coords
    assert_true(x_res > 0 and y_res > 0,
  File "/home/alicja/Desktop/projects/xcube/xcube/util/assertions.py", line 125, in assert_true
    raise exception_type(message)
RuntimeError: internal error: x_res and y_res could not be determined
2023-02-02 09:50:49,050 - tornado.application - ERROR - Uncaught exception GET /datasets?details=1 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/datasets?details=1', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/alicja/miniconda3/envs/xcube/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/alicja/Desktop/projects/xcube/xcube/server/webservers/tornado.py", line 354, in get
    await self._call_method('get', *args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/server/webservers/tornado.py", line 374, in _call_method
    method(*args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/routes.py", line 77, in get
    response = get_datasets(self.ctx,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/controllers.py", line 145, in get_datasets
    get_dataset(ctx, ds_id,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/controllers.py", line 187, in get_dataset
    ml_ds = ctx.get_ml_dataset(ds_id)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 181, in get_ml_dataset
    ml_dataset, _ = self._get_dataset_entry(ds_id)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 599, in _get_dataset_entry
    self._set_dataset_entry(self._create_dataset_entry(ds_id))
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 612, in _create_dataset_entry
    ml_dataset = self._open_ml_dataset(dataset_config)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 640, in _open_ml_dataset
    ml_dataset = BaseMultiLevelDataset(dataset)
  File "/home/alicja/Desktop/projects/xcube/xcube/core/mldataset/base.py", line 63, in __init__
    grid_mapping = GridMapping.from_dataset(base_dataset,
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/base.py", line 669, in from_dataset
    return new_grid_mapping_from_dataset(
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/dataset.py", line 65, in new_grid_mapping_from_dataset
    grid_mappings = [
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/dataset.py", line 66, in <listcomp>
    new_grid_mapping_from_coords(x_coords=gmp.coords.x,
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/coords.py", line 257, in new_grid_mapping_from_coords
    assert_true(x_res > 0 and y_res > 0,
  File "/home/alicja/Desktop/projects/xcube/xcube/util/assertions.py", line 125, in assert_true
    raise exception_type(message)
RuntimeError: internal error: x_res and y_res could not be determined
[E 2023-02-02 09:50:49,050 tornado.application] Uncaught exception GET /datasets?details=1 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/datasets?details=1', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/alicja/miniconda3/envs/xcube/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/alicja/Desktop/projects/xcube/xcube/server/webservers/tornado.py", line 354, in get
    await self._call_method('get', *args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/server/webservers/tornado.py", line 374, in _call_method
    method(*args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/routes.py", line 77, in get
    response = get_datasets(self.ctx,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/controllers.py", line 145, in get_datasets
    get_dataset(ctx, ds_id,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/controllers.py", line 187, in get_dataset
    ml_ds = ctx.get_ml_dataset(ds_id)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 181, in get_ml_dataset
    ml_dataset, _ = self._get_dataset_entry(ds_id)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 599, in _get_dataset_entry
    self._set_dataset_entry(self._create_dataset_entry(ds_id))
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 612, in _create_dataset_entry
    ml_dataset = self._open_ml_dataset(dataset_config)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/datasets/context.py", line 640, in _open_ml_dataset
    ml_dataset = BaseMultiLevelDataset(dataset)
  File "/home/alicja/Desktop/projects/xcube/xcube/core/mldataset/base.py", line 63, in __init__
    grid_mapping = GridMapping.from_dataset(base_dataset,
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/base.py", line 669, in from_dataset
    return new_grid_mapping_from_dataset(
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/dataset.py", line 65, in new_grid_mapping_from_dataset
    grid_mappings = [
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/dataset.py", line 66, in <listcomp>
    new_grid_mapping_from_coords(x_coords=gmp.coords.x,
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/coords.py", line 257, in new_grid_mapping_from_coords
    assert_true(x_res > 0 and y_res > 0,
  File "/home/alicja/Desktop/projects/xcube/xcube/util/assertions.py", line 125, in assert_true
    raise exception_type(message)
RuntimeError: internal error: x_res and y_res could not be determined
[E 2023-02-02 09:50:49,053 tornado.access] 500 GET /datasets?details=1 (127.0.0.1) 17934.43ms
[E 2023-02-02 09:50:49,053 tornado.access] 500 GET /datasets?details=1 (127.0.0.1) 17934.43ms
2023-02-02 09:50:49,053 - tornado.access - ERROR - 500 GET /datasets?details=1 (127.0.0.1) 17934.43ms
[E 2023-02-02 09:50:49,053 tornado.access] 500 GET /datasets?details=1 (127.0.0.1) 17934.43ms
[I 2023-02-02 09:50:49,188 tornado.access] 304 GET /colorbars (127.0.0.1) 18067.60ms
[I 2023-02-02 09:50:49,188 tornado.access] 304 GET /colorbars (127.0.0.1) 18067.60ms
2023-02-02 09:50:49,188 - tornado.access - INFO - 304 GET /colorbars (127.0.0.1) 18067.60ms
[I 2023-02-02 09:50:49,188 tornado.access] 304 GET /colorbars (127.0.0.1) 18067.60ms
```

**Comment by AliceBalfanz** [comment]
I'd like to reopen this issue: 

`xcube.core.store.error.DataStoreError: Failed to open dataset 'some-data.zarr': unable to decode time units 'days since 2022-04-01 00:00:00' with "calendar 'proleptic_gregorian'". Try opening your dataset with decode_times=False or installing cftime if it is not installed.`

The dataset was not properly updated with new input data and got corrupted. Instead of skipping this dataset and displaying the others, no datasets are served and the server returns "500 GET /api/datasets?details=1" 

xcube Viewer version 1.7.2
xcube Server version 1.13.2

**Comment by forman** [comment]
Dealt with separately.
